
//----------------------------------------------------
// project: GR4J     header generated by YAO version 9.2.1.0
//----------------------------------------------------

#ifndef YAOPROJECT_GR4J_PROJECT_HPP_INCLUDED
#define YAOPROJECT_GR4J_PROJECT_HPP_INCLUDED
/*! 
 * \file ProjectGR4J.hpp
 * \brief Declaration of GR4J 's ProjectGR4J project
 * $Id$
 */
/*
Copyright or © or Copr. MMSA team, LOCEAN Paris (2011)

This software is a framework for variational data assimilation in
numerical models.

This software is governed by the CeCILL license under French law and
abiding by the rules of distribution of free software.  You can  use,
modify and/ or redistribute the software under the terms of the CeCILL
license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info".

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author,  the holder of the
economic rights,  and the successive licensors  have only  limited
liability.

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or
data to be ensured and,  more generally, to use and operate it in the
same conditions as regards security.

The fact that you are presently reading this means that you have had
knowledge of the CeCILL license and that you accept its terms.

YAO website : http://www.locean-ipsl.upmc.fr/~yao/
Contact : yao@locean-ipsl.upmc.fr
*/

#include "Project.hpp"
#include "Model.hpp"
#include "TrajectoryTpar.hpp"
#include "TrajectoryTm.hpp"

using namespace yaoProject;

namespace GR4J
{

class ProjectGR4J: public Project
{
  void initialize();

  int setState(char *nmmod, YREAL val);
  #ifdef YO_DUAL
  int setError(char *nmmod, YREAL val);
  #endif
};


void ProjectGR4J::initialize()
{
  activeModel = new Model;
  Trajectory *t;
  Space *s;
  Module *m;

  // Tpar trajectory creation
  t = new TrajectoryTpar();
  activeModel->addTrajectory (t);

  // Tm trajectory creation
  t = new TrajectoryTm();
  activeModel->addTrajectory (t);



  // Sm space creation
  s = new Space();
  strcpy (s->name, "Sm");
  s->type = 'M';
  s->axi = 1;
  s->axj = 0;
  s->axk = 0;
  s->trajectory = activeModel->getTrajectory((char *)"Tm");
  activeModel->addSpace (s);

  // Spar space creation
  s = new Space();
  strcpy (s->name, "Spar");
  s->type = 'M';
  s->axi = 1;
  s->axj = 0;
  s->axk = 0;
  s->trajectory = activeModel->getTrajectory((char *)"Tpar");
  activeModel->addSpace (s);



  // X1 space creation
  m = new Module();
  strcpy (m->name, "X1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 0;
  m->nb_stout = 1;
  m->nb_time = 0;
  m->is_cout = 0;
  m->is_target = 1;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 0;
  m->trajectory = activeModel->getTrajectory((char *)"Tpar");
  m->space = activeModel->getSpace((char *)"Spar");
  activeModel->addModule (m);
  m->state = &YS1Y_X1;
  m->gradient = &YG1Y_X1;

  m->wish = &YW1Y_X1;
  m->epsilon = &YE1Y_X1;
  // X2 space creation
  m = new Module();
  strcpy (m->name, "X2");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 0;
  m->nb_stout = 1;
  m->nb_time = 0;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 0;
  m->trajectory = activeModel->getTrajectory((char *)"Tpar");
  m->space = activeModel->getSpace((char *)"Spar");
  activeModel->addModule (m);
  m->state = &YS1Y_X2;
  m->gradient = &YG1Y_X2;

  // X3 space creation
  m = new Module();
  strcpy (m->name, "X3");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 0;
  m->nb_stout = 1;
  m->nb_time = 0;
  m->is_cout = 0;
  m->is_target = 1;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 0;
  m->trajectory = activeModel->getTrajectory((char *)"Tpar");
  m->space = activeModel->getSpace((char *)"Spar");
  activeModel->addModule (m);
  m->state = &YS1Y_X3;
  m->gradient = &YG1Y_X3;

  m->wish = &YW1Y_X3;
  m->epsilon = &YE1Y_X3;
  // X4 space creation
  m = new Module();
  strcpy (m->name, "X4");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 0;
  m->nb_stout = 1;
  m->nb_time = 0;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 0;
  m->trajectory = activeModel->getTrajectory((char *)"Tpar");
  m->space = activeModel->getSpace((char *)"Spar");
  activeModel->addModule (m);
  m->state = &YS1Y_X4;
  m->gradient = &YG1Y_X4;

  // P space creation
  m = new Module();
  strcpy (m->name, "P");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 0;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 0;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_P;
  m->gradient = &YG1Y_P;

  // E space creation
  m = new Module();
  strcpy (m->name, "E");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 0;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 0;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_E;
  m->gradient = &YG1Y_E;

  // INTERC space creation
  m = new Module();
  strcpy (m->name, "INTERC");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 2;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_INTERC;
  m->gradient = &YG1Y_INTERC;

  // SX1 space creation
  m = new Module();
  strcpy (m->name, "SX1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_SX1;
  m->gradient = &YG1Y_SX1;

  // PNX1 space creation
  m = new Module();
  strcpy (m->name, "PNX1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_PNX1;
  m->gradient = &YG1Y_PNX1;

  // ENX1 space creation
  m = new Module();
  strcpy (m->name, "ENX1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_ENX1;
  m->gradient = &YG1Y_ENX1;

  // tanhPS space creation
  m = new Module();
  strcpy (m->name, "tanhPS");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 1;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_tanhPS;
  m->gradient = &YG1Y_tanhPS;

  // tanhES space creation
  m = new Module();
  strcpy (m->name, "tanhES");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 1;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_tanhES;
  m->gradient = &YG1Y_tanhES;

  // PS1 space creation
  m = new Module();
  strcpy (m->name, "PS1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 5;
  m->nb_stout = 2;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_PS1;
  m->gradient = &YG1Y_PS1;

  // PS2 space creation
  m = new Module();
  strcpy (m->name, "PS2");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 3;
  m->nb_stout = 2;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_PS2;
  m->gradient = &YG1Y_PS2;

  // PS3 space creation
  m = new Module();
  strcpy (m->name, "PS3");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 5;
  m->nb_stout = 2;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_PS3;
  m->gradient = &YG1Y_PS3;

  // MS1 space creation
  m = new Module();
  strcpy (m->name, "MS1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 3;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_MS1;
  m->gradient = &YG1Y_MS1;

  // MS21 space creation
  m = new Module();
  strcpy (m->name, "MS21");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 1;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_MS21;
  m->gradient = &YG1Y_MS21;

  // MS23 space creation
  m = new Module();
  strcpy (m->name, "MS23");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_MS23;
  m->gradient = &YG1Y_MS23;

  // MS24 space creation
  m = new Module();
  strcpy (m->name, "MS24");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_MS24;
  m->gradient = &YG1Y_MS24;

  // MS3 space creation
  m = new Module();
  strcpy (m->name, "MS3");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_MS3;
  m->gradient = &YG1Y_MS3;

  // PR space creation
  m = new Module();
  strcpy (m->name, "PR");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 3;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_PR;
  m->gradient = &YG1Y_PR;

  // Q9 space creation
  m = new Module();
  strcpy (m->name, "Q9");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 31;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_Q9;
  m->gradient = &YG1Y_Q9;

  // Q1 space creation
  m = new Module();
  strcpy (m->name, "Q1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 31;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_Q1;
  m->gradient = &YG1Y_Q1;

  // F space creation
  m = new Module();
  strcpy (m->name, "F");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 3;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_F;
  m->gradient = &YG1Y_F;

  // QR space creation
  m = new Module();
  strcpy (m->name, "QR");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_QR;
  m->gradient = &YG1Y_QR;

  // RQ9F space creation
  m = new Module();
  strcpy (m->name, "RQ9F");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 3;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_RQ9F;
  m->gradient = &YG1Y_RQ9F;

  // R1 space creation
  m = new Module();
  strcpy (m->name, "R1");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 1;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_R1;
  m->gradient = &YG1Y_R1;

  // R2 space creation
  m = new Module();
  strcpy (m->name, "R2");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_R2;
  m->gradient = &YG1Y_R2;

  // RX3 space creation
  m = new Module();
  strcpy (m->name, "RX3");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_RX3;
  m->gradient = &YG1Y_RX3;

  // RX32 space creation
  m = new Module();
  strcpy (m->name, "RX32");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 1;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_RX32;
  m->gradient = &YG1Y_RX32;

  // Q1QF space creation
  m = new Module();
  strcpy (m->name, "Q1QF");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_Q1QF;
  m->gradient = &YG1Y_Q1QF;

  // QD space creation
  m = new Module();
  strcpy (m->name, "QD");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 1;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 0;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_QD;
  m->gradient = &YG1Y_QD;

  // QS space creation
  m = new Module();
  strcpy (m->name, "QS");
  m->dim = 1;
  m->axi = 1;
  m->axj = 0;
  m->axk = 0;
  m->nb_input = 2;
  m->nb_stout = 1;
  m->nb_time = 2416;
  m->is_cout = 1;
  m->is_target = 0;
  m->deb_target = 0;
  m->end_target = 0;
  m->scoef = 1.000000;
  m->bcoef = 1.000000;
  m->pcoef = 1.000000;
  m->qcoef = 1.000000;
  m->ctrord = 1;
  m->trajectory = activeModel->getTrajectory((char *)"Tm");
  m->space = activeModel->getSpace((char *)"Sm");
  activeModel->addModule (m);
  m->state = &YS1Y_QS;
  m->gradient = &YG1Y_QS;

  m->wish = &YW1Y_QS;

}


int ProjectGR4J::setState(char *nmmod, YREAL val)
{
	int codret=0; int all=0;
	if (!strcmp(nmmod, (char *) "Y#A")) all=1;
	if (!strcmp(nmmod, (char *) "X1") || all)
	{  Ysetstate_X1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "X2") || all)
	{  Ysetstate_X2(val);codret=1;}
	if (!strcmp(nmmod, (char *) "X3") || all)
	{  Ysetstate_X3(val);codret=1;}
	if (!strcmp(nmmod, (char *) "X4") || all)
	{  Ysetstate_X4(val);codret=1;}
	if (!strcmp(nmmod, (char *) "P") || all)
	{  Ysetstate_P(val);codret=1;}
	if (!strcmp(nmmod, (char *) "E") || all)
	{  Ysetstate_E(val);codret=1;}
	if (!strcmp(nmmod, (char *) "INTERC") || all)
	{  Ysetstate_INTERC(val);codret=1;}
	if (!strcmp(nmmod, (char *) "SX1") || all)
	{  Ysetstate_SX1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "PNX1") || all)
	{  Ysetstate_PNX1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "ENX1") || all)
	{  Ysetstate_ENX1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "tanhPS") || all)
	{  Ysetstate_tanhPS(val);codret=1;}
	if (!strcmp(nmmod, (char *) "tanhES") || all)
	{  Ysetstate_tanhES(val);codret=1;}
	if (!strcmp(nmmod, (char *) "PS1") || all)
	{  Ysetstate_PS1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "PS2") || all)
	{  Ysetstate_PS2(val);codret=1;}
	if (!strcmp(nmmod, (char *) "PS3") || all)
	{  Ysetstate_PS3(val);codret=1;}
	if (!strcmp(nmmod, (char *) "MS1") || all)
	{  Ysetstate_MS1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "MS21") || all)
	{  Ysetstate_MS21(val);codret=1;}
	if (!strcmp(nmmod, (char *) "MS23") || all)
	{  Ysetstate_MS23(val);codret=1;}
	if (!strcmp(nmmod, (char *) "MS24") || all)
	{  Ysetstate_MS24(val);codret=1;}
	if (!strcmp(nmmod, (char *) "MS3") || all)
	{  Ysetstate_MS3(val);codret=1;}
	if (!strcmp(nmmod, (char *) "PR") || all)
	{  Ysetstate_PR(val);codret=1;}
	if (!strcmp(nmmod, (char *) "Q9") || all)
	{  Ysetstate_Q9(val);codret=1;}
	if (!strcmp(nmmod, (char *) "Q1") || all)
	{  Ysetstate_Q1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "F") || all)
	{  Ysetstate_F(val);codret=1;}
	if (!strcmp(nmmod, (char *) "QR") || all)
	{  Ysetstate_QR(val);codret=1;}
	if (!strcmp(nmmod, (char *) "RQ9F") || all)
	{  Ysetstate_RQ9F(val);codret=1;}
	if (!strcmp(nmmod, (char *) "R1") || all)
	{  Ysetstate_R1(val);codret=1;}
	if (!strcmp(nmmod, (char *) "R2") || all)
	{  Ysetstate_R2(val);codret=1;}
	if (!strcmp(nmmod, (char *) "RX3") || all)
	{  Ysetstate_RX3(val);codret=1;}
	if (!strcmp(nmmod, (char *) "RX32") || all)
	{  Ysetstate_RX32(val);codret=1;}
	if (!strcmp(nmmod, (char *) "Q1QF") || all)
	{  Ysetstate_Q1QF(val);codret=1;}
	if (!strcmp(nmmod, (char *) "QD") || all)
	{  Ysetstate_QD(val);codret=1;}
	if (!strcmp(nmmod, (char *) "QS") || all)
	{  Ysetstate_QS(val);codret=1;}
	return(codret);


}
#ifdef YO_DUAL
int ProjectGR4J::setError(char *nmmod, YREAL val)
{

}
#endif

}
#endif
